#!/bin/sh

# $Id: ovs-init,v 1.2 2007-08-26 17:02:21 kiwi Exp $
# example init script for ovs 
#
# chkconfig: 2345 82 28
# description: ovs log grapher.
#
# processname: ovs.pl
# pidfile: /var/run/ovs.pid


PATH=/bin:/usr/bin
OVS_PL=/usr/local/bin/ovs.pl
MAIL_LOG=/var/log/syslog
PID_FILE=/var/run/ovs.pid
RRD_DIR=/var/lib

case "$1" in
'start')
	echo "Starting mail statistics grapher: ovs";
	nice -19 $OVS_PL -l $MAIL_LOG -d \
		--daemon-pid=$PID_FILE --daemon-rrd=$RRD_DIR
	;;

'stop')
	echo "Stopping mail statistics grapher: ovs";
	if [ -f $PID_FILE ]; then
		kill `cat $PID_FILE`
		rm $PID_FILE
	else
		echo "ovs not running";
	fi
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;

esac
exit 0
